### ISSUE TITLE
Revue de sécurité

### ISSUE THREAD

**Issue by Seliaste** [Kiavain/ACL-2024-KiAvenir#27]

**Comment by LowanFr** [comment]
Est-ce que je clos l'issue en la renommant en parlant des tests, ou non.
Car en soit, j'ai fait aussi de la revue de sécurité dans la code review que j'ai fait.

**Comment by Seliaste** [comment]
> Est-ce que je clos l'issue en la renommant en parlant des tests, ou non. Car en soit, j'ai fait aussi de la revue de sécurité dans la code review que j'ai fait.

ouais tu peux pardon je pensais la refaire après le merge de la branche #11 mais en fait t'as déjà fait donc tu peux juste clore en marquant que c toi qui était assigné
